baseURL: "https://tjards.github.io/"
languageCode: en-us
title: research notes
theme: PaperMod

pagination:
  pagerSize: 3

markup:
  goldmark:
      renderer:
        hardWraps: false
        unsafe: true
        xhtml: false
  defaultMarkdownHandlers:
    mathjax: true

menu:
  main: 
    #- identifier: categories
    #  name: categories
    #  url: /categories/
    #  weight: 15
    - identifier: about
      name: about me
      url: /about/
      weight: 5
    - identifier: archives 
      name: posts
      url: /archives/
      weight: 10
    - identifier: publications
      name: publications
      url: https://scholar.google.com/citations?user=RGlv4ZUAAAAJ&hl=en
      weight: 30
    - identifier: projects
      name: projects
      url: /projects/
      weight: 15

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:

  homeInfoParams:
    Title: research notes
    Content: thoughts on robotics, control, and artificial intelligence

  assets:
    css:
      - css/style.css
    
    favicon: "img/favicon-quarrg.ico"
    favicon16x16: "img/favicon-quarrg.png"
    favicon32x32: "img/favicon-quarrg.png"


  socialIcons:
    - name: github
      url: "https://github.com/tjards"
    - name: linkedin
      url: "https://www.linkedin.com/in/p-travis-jardine-403b3a148/"
    - name: researchgate
      url: "https://www.researchgate.net/profile/Peter-Jardine"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=RGlv4ZUAAAAJ&hl=en"

  # defaultTheme: light
  # defaultTheme: dark
  # defaultTheme: auto
  defaultTheme: light 

  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Personal Website"
  keywords: ["robotics", "control", "swarming", "artificial intelligence"]
  author: tjards
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 Jan 2006"
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  #assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    #favicon: "<link / abs url>"
    #favicon16x16: "<link / abs url>"
    #favicon32x32: "<link / abs url>"
    #apple_touch_icon: "<link / abs url>"
    #safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    #icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

 # analytics:
 #   google:
 #     SiteVerificationTag: "XYZabc"
 #   bing:
 #     SiteVerificationTag: "XYZabc"
 #   yandex:
 #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  #fuseOpts:
  #  isCaseSensitive: false
  #  shouldSort: true
  #  location: 0
  #  distance: 1000
  #  threshold: 0.4
  #  minMatchCharLength: 0
  #  limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
  #  keys: ["title", "permalink", "summary", "content"]

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
#pygmentsUseClasses: true
#markup:
#  highlight:
#    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

